# Generated by Django 6.1 on 2026-10-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
